### ISSUE TITLE
Get Going instructions vague and possibly incorrect

### ISSUE THREAD

**Issue by aaronroberson** [radify/PR.js#6]
I performed the following:

`mkdir jspmtest && cd jspmtest`
`npm install -g gulp jspm`
`npm install`
`jspm install` (follow prompts and accept defaults)

Running `gulp serve` returns **No gulpfile found**. 

**Questions**
- Do I run `jspm install` from a current app root that already has a gulpfile.js?
  *\* If so, will PR.js highjack or override my existing `gulp serve` task?
- How is setting up PR.js locally differ from the hosted version (https://radify.github.io/)?
  *\* If I set up PR.js locally, will I be able to use my private repository?

**Comment by nateabele** [comment]
> I performed the following [...]

My experience has always been that installation instructions are assumed to be run from the project directory, after cloning. I'm open to suggestions on how to make it more clear that this is the intent.

> Do I run jspm install from a current app root that already has a gulpfile.js? *\* If so, will PR.js highjack or override my existing gulp serve task?

Nope, JSPM works just like NPM. You clone the project and install dependencies. It has its own independent `Gulpfile`.

> How is setting up PR.js locally differ from the hosted version (https://radify.github.io/)?

Right now the only benefit to cloning it locally is to hack on the validation rules or contribute to tasks on the [roadmap](https://github.com/radify/PR.js#roadmap). :smile:

> If I set up PR.js locally, will I be able to use my private repository?

Nope, we need to add GitHub auth for that (also on the roadmap). Should have time to implement it soon.

**Comment by jfmercer** [comment]
Cf. #12.
